version: '3.8'
services:
  
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:80 manage:app
    expose:
      - 80
    env_file:
      - ./.env.cloud