version: '3.8'

services:
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - web
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    user: root
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    deploy:
        resources:
            limits:
              cpus: '2'
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5433:5432
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M
  worker:
    build: 
      context: ./services/web/tasks
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: celery -A tasks.music_task worker --loglevel=info
    volumes:
      - ./services/web/:/usr/src/app/
      - media_volume:/home/app/web/project/media
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis-local
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M

  redis-local:
    image: redis/redis-stack-server:latest

    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: