runtime: python

env: flex
runtime_config:
    python_version: 3.7

entrypoint: gunicorn -b :8080 manage:app
env_variables:
    DATABASE_URL: "[Completar]"
    FLASK_APP: "project/__init__.py"
    FLASK_DEBUG: "1"
    SQL_HOST: "10.89.208.3"
    SQL_PORT: "5432"
    DATABASE: "db_music_converted"
    APP_FOLDER: "/home/app/web"
    SECRET_KEY: <secret>
    ENDPOINT_CONVERTED_DB: "http://web:5001/api/converted"
    GCP_PROJECT_NAME: "devopslsolier"
    TARGET_TOPIC: "converter-topic"
    BUCKET_NAME: "music-converter-prueba-1"

automatic_scaling:
    max_num_instances: 1