FROM gcr.io/google_appengine/python
RUN apt-get -y update && apt-get install -y --no-install-recommends ffmpeg

# ENV VIRTUAL_ENV /env
# ENV PATH /env/bin:$PATH

# WORKDIR /usr/src/app

# RUN virtualenv /env
# RUN pip install --upgrade pip
# COPY ./requirements.txt .
# RUN pip install -r requirements.txt

# CMD python3 -m tasks.music_task.py